#!/usr/bin/env python3
"""LinkPrice 오퍼월(쇼핑적립) API → affiliate.json 자동 생성.

동작:
  1. 오퍼월 메인 호출로 머천트 목록(offerwall_cards) 획득
  2. 머천트별 상세 호출로 click_url(실제 제휴 딥링크) 획득
  3. 우리 앱(모바일 RN Linking) 부적합 머천트(PC전용 등) 필터
  4. AffiliateOffer 형식으로 변환해 affiliate.json 덮어쓰기

안전장치(가장 중요):
  - 오퍼월 미설정(code != 0, 예: -6) → 기존 affiliate.json 보존(no-op)
  - 머천트 0 / 필터 후 유효 오퍼 0 → 보존(no-op)
  - 호출 실패 → 보존(no-op)
  => 오퍼월이 켜지기 전까지는 수동 오퍼(컬리·CJ)가 그대로 유지된다.

규약 근거: ReviewSupporter/reports/어필리에이트_머천트_규약_종합_LinkPrice20_20260624.md
"""
import json
import os
import sys
import urllib.parse
import urllib.request

A_ID = "A100705176"          # 우리 LinkPrice 어필리에이트 코드
U_ID = "rs_auto"             # 익명 고정(무리워드 모델 — 유저별 적립 안 줌)
BASE = "https://api.linkprice.com/offerwall"
OUT = os.path.join(os.path.dirname(__file__), "..", "affiliate.json")
MAX_OFFERS = 10              # AffiliateSection 코드 상한과 일치
TIMEOUT = 20

# 우리 앱은 Linking.openURL로 모바일웹/머천트앱을 연다.
# "실적 미인정" 머천트는 클릭돼도 수익 0 → 오퍼에서 제외.
# (근거=어필리에이트_머천트_규약_종합_LinkPrice20)
APP_BLOCKLIST = {
    "gmarket",   # PC만 인정 → 모바일 앱 수익 0
}
# 참고(유지하되 주의): hmall=iOS미인정, lotteon/yes24/kbbook=앱미인정이나
# 모바일웹 fallback 시 인정 가능 → 블록하지 않음. 손실 보이면 위 set에 추가.


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": "rs-affiliate-bot/1.0"})
    with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
        return json.loads(r.read().decode("utf-8"))


def build_offers(cards):
    offers = []
    for c in cards:
        mid = c.get("merchant_id")
        if not mid or mid in APP_BLOCKLIST:
            continue
        det_url = "%s/%s/detail?%s" % (
            BASE, A_ID,
            urllib.parse.urlencode({"mode": "json", "u_id": U_ID, "m_id": mid}),
        )
        try:
            det = fetch(det_url)
        except Exception as e:
            print("[warn] %s 상세 호출 실패: %s" % (mid, e), file=sys.stderr)
            continue
        click = det.get("click_url")
        if not click or not click.startswith("http"):
            print("[warn] %s click_url 없음 → 제외" % mid, file=sys.stderr)
            continue
        name = (c.get("site_name") or mid).strip()
        comm = (c.get("max_commission") or "").strip()
        offer = {
            "id": "lp-%s" % mid,
            "title": name,
            "subtitle": ("최대 적립 %s" % comm) if comm else "쇼핑적립",
            "url": click,
            "merchant": mid,
        }
        banner = c.get("banner_url")
        if banner and banner.startswith("http"):
            offer["imageUrl"] = banner
        offers.append(offer)
        if len(offers) >= MAX_OFFERS:
            break
    return offers


def main():
    main_url = "%s/%s?%s" % (
        BASE, A_ID, urllib.parse.urlencode({"mode": "json", "u_id": U_ID})
    )
    try:
        data = fetch(main_url)
    except Exception as e:
        print("[skip] 오퍼월 호출 실패: %s → 기존 affiliate.json 보존" % e, file=sys.stderr)
        return 0

    code = data.get("code") if isinstance(data, dict) else None
    if code is not None and code != 0:
        print("[skip] 오퍼월 미설정 (code=%s, msg=%s) → 기존 유지" % (code, data.get("msg")))
        return 0

    cards = (data.get("offerwall_cards") or []) if isinstance(data, dict) else []
    if not cards:
        print("[skip] 머천트 0 → 기존 affiliate.json 보존")
        return 0

    offers = build_offers(cards)
    if not offers:
        print("[skip] 필터 후 유효 오퍼 0 → 기존 유지")
        return 0

    out = {
        "_comment": (
            "AUTO-GENERATED by scripts/build_affiliate.py (LinkPrice 오퍼월 API, 하루 1회). "
            "수동 편집은 다음 cron에 덮어써짐. 머천트 필터 근거=ReviewSupporter/reports/"
            "어필리에이트_머천트_규약_종합_LinkPrice20_20260624.md"
        ),
        "offers": offers,
    }
    path = os.path.abspath(OUT)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("[ok] %d개 오퍼 생성: %s" % (len(offers), ", ".join(o["merchant"] for o in offers)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
